A silly Python script that generates verse in arbitrary rhyme and stress patterns. 

The base is the "pronouncing" library ( pronouncing.readthedocs.io ), a Python library for parsing the CMU pronunciation dictionary (http://www.speech.cs.cmu.edu/cgi-bin/cmudict). You need to install this first - `pip install pronouncing` will do it.

Using the entire dictionary produces hard-to-read stuff with lots of obscure words, so I use a list of the 3,000 most common words in the English language to build a sub-dictionary.

The method for building a random verse relies a lot on trial and error because of the "greedy" algorithm - given the limited set of words, there is often no word that fits the previous words in the verse, especially taking rhyme into account. If that happens, it starts over with a new random verse. This is common, especially with longer verses like sonnets, so it might have several "failures" before it spits out something. It's fast enough that this lack of efficiency doesn't matter much.

The most expensive part is generating the list of rhymes and pronunciations for the 3,000 words at the beginning. After that, it's all pretty quick.

This is quick and dirty and was produced during baby naps while I was on leave from work. This is not intended as an example of high-quality production code!

If you're masochistic or sadistic enough, and you also use a Mac, you can switch around the comments in the `words_to_line` function, and your computer will read the verse out to you directly, spitting mad fire directly.

Here is some sample output: (n.b. as noted in xkcd and achewood, all ballads can be sung to the tune of Gilligan's Island)

----
STORYBOOK
in southern everywhere sustain,
express beyond recruit contain,
establish criticize in task,
unlike defensive finish mask,

in useful share surprising quote,
detect debate the chicken coat,
department overcome unlike,
horizon solar doubt and strike,

athletic realize confirm,
construction circumstance in firm,
and finger telephone and shock,
the interest substantial clock,

in calculate supposed create,
direct expect attractive wait,
a anymore produce above,
electric cap assumption glove,

familiar frequent shelter hell,
distinct detailed within and yell,
exchange a episode defend,
ideal return whereas the trend,

expensive street decline a scope,
convince and notion album rope,
permit deliver term career,
in scholarship and engineer,

DOUCLEDACTYL
study confusion in,
match a advance a a,
settlement properly,
dominant rail,
serious funny in,
motion survivor the,
million extend in the,
greatest detail,

parking and possible,
knife a the voter the,
soldier commander in,
differ direct,
chemical factory,
rhythm apart a a,
hundred discover the,
twin a detect,

fewer a instrument,
concept in elderly,
violence city in,
for a success,
honey confusion in,
meter moreover and,
handle genetic a,
medium mess,

policy surgery,
entrance subject a the,
heavily possible,
reason and yet,
matter reflection in,
nose and and glad in in,
audience leather a,
talent the get,

governor citizen,
register argument,
instrument famous in,
annual trade,
frequently symbol the,
tell in the true the the,
ultimate question in,
possible blade,

specialist violate,
toy the in threaten in,
industry clinical,
parent the moon,
sugar and journey the,
owe in essay the in,
series official in,
typical soon,

BALLAD
contain surprise in darkness she,
surround believe in nerve,
tremendous generate degree,
the car a speed a serve,

resemble press respect in nod,
appoint commitment glove,
agenda quarterback the odd,
decade a wealth above,

a finger bottom mixture phase,
designer yes in clue,
react today the planet phrase,
reform accept pursue,

the billion greatest ah technique,
a language anyway,
the mass and source piano peak,
ahead adult survey,

exchange attorney kind relief,
and slightly pause prevent,
divorce entire tent belief,
respondent threaten tent,

the case upon frustration score,
prescription pet respect,
location border only floor,
expect possess affect,

SONNETS
moreover after party metal teen,
resolve release container village case,
afford tradition used in absence clean,
in rating face the where the fishing pace,
the naked circumstance persuade unique,
in show develop whole create a week,
explain exhibit movement prison peak,
extent statistics everyday technique,
device frustration universe a since,
surprising calculate dependent so,
embrace commander photograph convince,
confusion forward dialogue hello,
in partner killer fail and meaning cheap,
the manage drive the send concerned asleep,

and drag and parent alcohol exist,
in alcohol a via jury strength,
surprised a junior check severe and list,
romantic clothes and recommend a length,
and poll prevent a radio until,
equipment chart offensive second raw,
enforcement case defendant nose a skill,
provider regulate collective ah,
evolve commission yesterday belong,
in problem organize a full in slice,
acknowledge indicate the special long,
abroad in grand prepare explore advice,
encounter room in can behavior might,
division much in revenue tonight,

aggressive glove the cheap attempt a light,
abandon title coast regime begin,
surround assistance everyone tonight,
surround genetic balance vote within,
profession who survivor anymore,
perform and sure suppose expand the term,
and hurt a atmosphere advance and floor,
discover hate a jump convince confirm,
beyond and patient winner six assess,
before above behavior loan hello,
the absolute appeal compare a yes,
refuse defeat in edge in undergo,
fifteen in hit the uniform proceed,
assist strategic ugly yours exceed,

disorder leadership assistant next,
today the educate in hide and now,
in concentrate a flame detect the text,
provision there aggressive thick in cow,
component reinforce acquire switch,
relate the hurt the educate campaign,
in see exposure painter silence pitch,
together jacket sad examine grain,
protect the gather bell exactly main,
in leather film expansion help explain,
preserve asleep advise employment plane,
specific justify employer chain,
and gate vacation dining battle block,
a grow extremely sound commercial knock,

HEROIC VERSE
and yesterday a stare already firm,
consumption membership defensive term,
a attitude offense production sand,
in wrong around reaction native band,
become elect a ski promote pretend,
employment speech profession recommend,
in concert left and port attempt report,
distinction chance around assistance short,
apartment type attach perspective bend,
resort assignment rich destruction spend,
whenever tight asleep in beauty most,
attractive uniform example ghost,
and lemon maker organize a coast,
accuse the organize and chicken post,
already operate collapse career,
arrangement saving photograph appear,
expect depend in room and super crew,
believe success herself idea clue,
approach request whereas result without,
appeal a priest predict precisely doubt,
agenda tone a dominate and roll,
conclude prepare the introduce control,
confusion former man convince regime,
a deer dependent tail perfect extreme,
a crisis bond unlikely concert cap,
in clean protection reach appearance snap,
a company regarding laugh himself,
retain belief in guarantee in shelf,
accomplish shower gate repeat the track,
and nonetheless advantage mouse attack,
consensus shock respond remaining growth,
computer cable wife survivor both,
collective capture move and ticket stake,
procedure high the heaven target sake,
explore completely constitute success,
offensive high because without and dress,
in patient interest equipment sleep,
in satisfy in more develop cheap,
in structure union theme condition take,
expansion park in belt relax mistake,

